spring:
  cache:
    ehcache:
      config: ehcache.xml
    type: ehcache
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 300